version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: joyeria_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: joyeria_db
    ports:
      - "5432:5432"
    volumes:
      - joyeria_data:/var/lib/postgresql/data

volumes:
  joyeria_data:
